import React from 'react'
import ReactDOM from 'react-dom/client'
import '@fontsource/eb-garamond/cyrillic.css'
import '@fontsource/eb-garamond/cyrillic-400-italic.css'
import '@fontsource/eb-garamond/cyrillic-600-italic.css'
import '@fontsource/eb-garamond/latin.css'
import '@fontsource/eb-garamond/latin-400-italic.css'
import '@fontsource/eb-garamond/latin-600-italic.css'
import '@fontsource/oswald/cyrillic.css'
import '@fontsource/oswald/latin.css'
import '@fontsource/space-grotesk/latin.css'
import App from './App.jsx'
import './styles.css'

ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>)
